#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReactivaPeru
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDReactivacion")]
	public partial class ReactivaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAdministrador(Administrador instance);
    partial void UpdateAdministrador(Administrador instance);
    partial void DeleteAdministrador(Administrador instance);
    partial void InsertCategoria(Categoria instance);
    partial void UpdateCategoria(Categoria instance);
    partial void DeleteCategoria(Categoria instance);
    partial void InsertDetalleProducto(DetalleProducto instance);
    partial void UpdateDetalleProducto(DetalleProducto instance);
    partial void DeleteDetalleProducto(DetalleProducto instance);
    partial void InsertEmpresa(Empresa instance);
    partial void UpdateEmpresa(Empresa instance);
    partial void DeleteEmpresa(Empresa instance);
    partial void InsertImagen(Imagen instance);
    partial void UpdateImagen(Imagen instance);
    partial void DeleteImagen(Imagen instance);
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertVendedor(Vendedor instance);
    partial void UpdateVendedor(Vendedor instance);
    partial void DeleteVendedor(Vendedor instance);
    #endregion
		
		public ReactivaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BDReactivacionConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ReactivaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReactivaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReactivaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReactivaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Administrador> Administrador
		{
			get
			{
				return this.GetTable<Administrador>();
			}
		}
		
		public System.Data.Linq.Table<Categoria> Categoria
		{
			get
			{
				return this.GetTable<Categoria>();
			}
		}
		
		public System.Data.Linq.Table<DetalleProducto> DetalleProducto
		{
			get
			{
				return this.GetTable<DetalleProducto>();
			}
		}
		
		public System.Data.Linq.Table<Empresa> Empresa
		{
			get
			{
				return this.GetTable<Empresa>();
			}
		}
		
		public System.Data.Linq.Table<Imagen> Imagen
		{
			get
			{
				return this.GetTable<Imagen>();
			}
		}
		
		public System.Data.Linq.Table<Producto> Producto
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Vendedor> Vendedor
		{
			get
			{
				return this.GetTable<Vendedor>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spActualizarDatosVendedor")]
		public ISingleResult<spActualizarDatosVendedorResult> spActualizarDatosVendedor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorreoV", DbType="VarChar(50)")] string correoV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreV", DbType="VarChar(50)")] string nombreV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApellidosV", DbType="VarChar(50)")] string apellidosV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelefonoV", DbType="VarChar(20)")] string telefonoV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DniV", DbType="VarChar(10)")] string dniV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correoV, nombreV, apellidosV, telefonoV, dniV);
			return ((ISingleResult<spActualizarDatosVendedorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAgregarImagen")]
		public ISingleResult<spAgregarImagenResult> spAgregarImagen([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdP", DbType="VarChar(5)")] string idP, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Image")] System.Data.Linq.Binary imagenI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreI", DbType="VarChar(50)")] string nombreI)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idP, imagenI, nombreI);
			return ((ISingleResult<spAgregarImagenResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAgregarVendedorEmpresa")]
		public ISingleResult<spAgregarVendedorEmpresaResult> spAgregarVendedorEmpresa([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorreoV", DbType="VarChar(50)")] string correoV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContraseniaV", DbType="VarChar(50)")] string contraseniaV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreV", DbType="VarChar(50)")] string nombreV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApellidosV", DbType="VarChar(50)")] string apellidosV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelefonoV", DbType="VarChar(20)")] string telefonoV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DniV", DbType="VarChar(10)")] string dniV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreE", DbType="VarChar(50)")] string nombreE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorreoE", DbType="VarChar(50)")] string correoE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RucE", DbType="VarChar(50)")] string rucE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelefonoE", DbType="VarChar(20)")] string telefonoE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DescripccionE", DbType="VarChar(300)")] string descripccionE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correoV, contraseniaV, nombreV, apellidosV, telefonoV, dniV, nombreE, correoE, rucE, telefonoE, descripccionE);
			return ((ISingleResult<spAgregarVendedorEmpresaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCambiarContraseniaVendedor")]
		public ISingleResult<spCambiarContraseniaVendedorResult> spCambiarContraseniaVendedor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(50)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContrasenaNueva", DbType="VarChar(50)")] string contrasenaNueva)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, contrasena, contrasenaNueva);
			return ((ISingleResult<spCambiarContraseniaVendedorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spEliminarImagen")]
		public ISingleResult<spEliminarImagenResult> spEliminarImagen([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdI", DbType="VarChar(5)")] string idI)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idI);
			return ((ISingleResult<spEliminarImagenResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spEliminarProducto")]
		public ISingleResult<spEliminarProductoResult> spEliminarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdP", DbType="Int")] System.Nullable<int> idP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idP);
			return ((ISingleResult<spEliminarProductoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spListarCategoria")]
		public ISingleResult<spListarCategoriaResult> spListarCategoria()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spListarCategoriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spListarEmpresa")]
		public ISingleResult<spListarEmpresaResult> spListarEmpresa()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spListarEmpresaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spListarImagen")]
		public ISingleResult<spListarImagenResult> spListarImagen()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spListarImagenResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spListarProducto")]
		public ISingleResult<spListarProductoResult> spListarProducto()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spListarProductoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spLoginVendedor")]
		public ISingleResult<spLoginVendedorResult> spLoginVendedor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasenia", DbType="VarChar(50)")] string contrasenia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correo, contrasenia);
			return ((ISingleResult<spLoginVendedorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spMisImagenes")]
		public ISingleResult<spMisImagenesResult> spMisImagenes([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usuarioV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuarioV);
			return ((ISingleResult<spMisImagenesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spListarCatalogo")]
		public ISingleResult<spListarCatalogoResult> spListarCatalogo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spListarCatalogoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spActualizarProducto")]
		public ISingleResult<spActualizarProductoResult> spActualizarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdP", DbType="Int")] System.Nullable<int> idP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdC", DbType="VarChar(5)")] string idC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreP", DbType="VarChar(50)")] string nombreP, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Image")] System.Data.Linq.Binary imagenI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MarcaP", DbType="VarChar(10)")] string marcaP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StockDP", DbType="Int")] System.Nullable<int> stockDP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioDP", DbType="Real")] System.Nullable<float> precioDP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DescripcionP", DbType="VarChar(300)")] string descripcionP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idP, idC, nombreP, imagenI, marcaP, stockDP, precioDP, descripcionP);
			return ((ISingleResult<spActualizarProductoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spMisProductos")]
		public ISingleResult<spMisProductosResult> spMisProductos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usuarioV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuarioV);
			return ((ISingleResult<spMisProductosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAgregarProducto")]
		public ISingleResult<spAgregarProductoResult> spAgregarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string correoV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdC", DbType="VarChar(5)")] string idC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreP", DbType="VarChar(50)")] string nombreP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MarcaP", DbType="VarChar(10)")] string marcaP, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Image")] System.Data.Linq.Binary imagenI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DescripcionP", DbType="VarChar(300)")] string descripcionP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StockDP", DbType="Int")] System.Nullable<int> stockDP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioDP", DbType="Real")] System.Nullable<float> precioDP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correoV, idC, nombreP, marcaP, imagenI, descripcionP, stockDP, precioDP);
			return ((ISingleResult<spAgregarProductoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spListarProductoDetalles")]
		public ISingleResult<spListarProductoDetallesResult> spListarProductoDetalles([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string idP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idP);
			return ((ISingleResult<spListarProductoDetallesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spListarfotosDeProducto")]
		public ISingleResult<spListarfotosDeProductoResult> spListarfotosDeProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string idP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idP);
			return ((ISingleResult<spListarfotosDeProductoResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAdministrador")]
	public partial class Administrador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdA;
		
		private string _NombreA;
		
		private string _ApellidoA;
		
		private string _DniA;
		
		private string _DireccionA;
		
		private string _TelefonoA;
		
		private string _CorreoA;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAChanging(string value);
    partial void OnIdAChanged();
    partial void OnNombreAChanging(string value);
    partial void OnNombreAChanged();
    partial void OnApellidoAChanging(string value);
    partial void OnApellidoAChanged();
    partial void OnDniAChanging(string value);
    partial void OnDniAChanged();
    partial void OnDireccionAChanging(string value);
    partial void OnDireccionAChanged();
    partial void OnTelefonoAChanging(string value);
    partial void OnTelefonoAChanged();
    partial void OnCorreoAChanging(string value);
    partial void OnCorreoAChanged();
    #endregion
		
		public Administrador()
		{
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdA", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdA
		{
			get
			{
				return this._IdA;
			}
			set
			{
				if ((this._IdA != value))
				{
					this.OnIdAChanging(value);
					this.SendPropertyChanging();
					this._IdA = value;
					this.SendPropertyChanged("IdA");
					this.OnIdAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreA", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreA
		{
			get
			{
				return this._NombreA;
			}
			set
			{
				if ((this._NombreA != value))
				{
					this.OnNombreAChanging(value);
					this.SendPropertyChanging();
					this._NombreA = value;
					this.SendPropertyChanged("NombreA");
					this.OnNombreAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoA", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ApellidoA
		{
			get
			{
				return this._ApellidoA;
			}
			set
			{
				if ((this._ApellidoA != value))
				{
					this.OnApellidoAChanging(value);
					this.SendPropertyChanging();
					this._ApellidoA = value;
					this.SendPropertyChanged("ApellidoA");
					this.OnApellidoAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DniA", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string DniA
		{
			get
			{
				return this._DniA;
			}
			set
			{
				if ((this._DniA != value))
				{
					this.OnDniAChanging(value);
					this.SendPropertyChanging();
					this._DniA = value;
					this.SendPropertyChanged("DniA");
					this.OnDniAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DireccionA", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DireccionA
		{
			get
			{
				return this._DireccionA;
			}
			set
			{
				if ((this._DireccionA != value))
				{
					this.OnDireccionAChanging(value);
					this.SendPropertyChanging();
					this._DireccionA = value;
					this.SendPropertyChanged("DireccionA");
					this.OnDireccionAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoA", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TelefonoA
		{
			get
			{
				return this._TelefonoA;
			}
			set
			{
				if ((this._TelefonoA != value))
				{
					this.OnTelefonoAChanging(value);
					this.SendPropertyChanging();
					this._TelefonoA = value;
					this.SendPropertyChanged("TelefonoA");
					this.OnTelefonoAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorreoA", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CorreoA
		{
			get
			{
				return this._CorreoA;
			}
			set
			{
				if ((this._CorreoA != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCorreoAChanging(value);
					this.SendPropertyChanging();
					this._CorreoA = value;
					this.SendPropertyChanged("CorreoA");
					this.OnCorreoAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Administrador", Storage="_Usuario", ThisKey="CorreoA", OtherKey="CorreoU", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Administrador.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Administrador.Add(this);
						this._CorreoA = value.CorreoU;
					}
					else
					{
						this._CorreoA = default(string);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TCategoria")]
	public partial class Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdC;
		
		private string _NombreC;
		
		private string _IdCatPadre;
		
		private EntitySet<Categoria> _Categoria1;
		
		private EntitySet<Producto> _Producto;
		
		private EntityRef<Categoria> _TCategoria1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCChanging(string value);
    partial void OnIdCChanged();
    partial void OnNombreCChanging(string value);
    partial void OnNombreCChanged();
    partial void OnIdCatPadreChanging(string value);
    partial void OnIdCatPadreChanged();
    #endregion
		
		public Categoria()
		{
			this._Categoria1 = new EntitySet<Categoria>(new Action<Categoria>(this.attach_Categoria1), new Action<Categoria>(this.detach_Categoria1));
			this._Producto = new EntitySet<Producto>(new Action<Producto>(this.attach_Producto), new Action<Producto>(this.detach_Producto));
			this._TCategoria1 = default(EntityRef<Categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdC", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdC
		{
			get
			{
				return this._IdC;
			}
			set
			{
				if ((this._IdC != value))
				{
					this.OnIdCChanging(value);
					this.SendPropertyChanging();
					this._IdC = value;
					this.SendPropertyChanged("IdC");
					this.OnIdCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreC
		{
			get
			{
				return this._NombreC;
			}
			set
			{
				if ((this._NombreC != value))
				{
					this.OnNombreCChanging(value);
					this.SendPropertyChanging();
					this._NombreC = value;
					this.SendPropertyChanged("NombreC");
					this.OnNombreCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCatPadre", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdCatPadre
		{
			get
			{
				return this._IdCatPadre;
			}
			set
			{
				if ((this._IdCatPadre != value))
				{
					if (this._TCategoria1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCatPadreChanging(value);
					this.SendPropertyChanging();
					this._IdCatPadre = value;
					this.SendPropertyChanged("IdCatPadre");
					this.OnIdCatPadreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Categoria", Storage="_Categoria1", ThisKey="IdC", OtherKey="IdCatPadre")]
		public EntitySet<Categoria> Categoria1
		{
			get
			{
				return this._Categoria1;
			}
			set
			{
				this._Categoria1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Producto", Storage="_Producto", ThisKey="IdC", OtherKey="IdC")]
		public EntitySet<Producto> Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				this._Producto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Categoria", Storage="_TCategoria1", ThisKey="IdCatPadre", OtherKey="IdC", IsForeignKey=true)]
		public Categoria TCategoria1
		{
			get
			{
				return this._TCategoria1.Entity;
			}
			set
			{
				Categoria previousValue = this._TCategoria1.Entity;
				if (((previousValue != value) 
							|| (this._TCategoria1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TCategoria1.Entity = null;
						previousValue.Categoria1.Remove(this);
					}
					this._TCategoria1.Entity = value;
					if ((value != null))
					{
						value.Categoria1.Add(this);
						this._IdCatPadre = value.IdC;
					}
					else
					{
						this._IdCatPadre = default(string);
					}
					this.SendPropertyChanged("TCategoria1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Categoria1(Categoria entity)
		{
			this.SendPropertyChanging();
			entity.TCategoria1 = this;
		}
		
		private void detach_Categoria1(Categoria entity)
		{
			this.SendPropertyChanging();
			entity.TCategoria1 = null;
		}
		
		private void attach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = this;
		}
		
		private void detach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TDetalleProducto")]
	public partial class DetalleProducto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdDP;
		
		private string _IdP;
		
		private System.Nullable<int> _StockDP;
		
		private float _PrecioDP;
		
		private string _EstadoDP;
		
		private EntityRef<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDPChanging(string value);
    partial void OnIdDPChanged();
    partial void OnIdPChanging(string value);
    partial void OnIdPChanged();
    partial void OnStockDPChanging(System.Nullable<int> value);
    partial void OnStockDPChanged();
    partial void OnPrecioDPChanging(float value);
    partial void OnPrecioDPChanged();
    partial void OnEstadoDPChanging(string value);
    partial void OnEstadoDPChanged();
    #endregion
		
		public DetalleProducto()
		{
			this._Producto = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDP", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdDP
		{
			get
			{
				return this._IdDP;
			}
			set
			{
				if ((this._IdDP != value))
				{
					this.OnIdDPChanging(value);
					this.SendPropertyChanging();
					this._IdDP = value;
					this.SendPropertyChanged("IdDP");
					this.OnIdDPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdP", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdP
		{
			get
			{
				return this._IdP;
			}
			set
			{
				if ((this._IdP != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPChanging(value);
					this.SendPropertyChanging();
					this._IdP = value;
					this.SendPropertyChanged("IdP");
					this.OnIdPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockDP", DbType="Int")]
		public System.Nullable<int> StockDP
		{
			get
			{
				return this._StockDP;
			}
			set
			{
				if ((this._StockDP != value))
				{
					this.OnStockDPChanging(value);
					this.SendPropertyChanging();
					this._StockDP = value;
					this.SendPropertyChanged("StockDP");
					this.OnStockDPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioDP", DbType="Real NOT NULL")]
		public float PrecioDP
		{
			get
			{
				return this._PrecioDP;
			}
			set
			{
				if ((this._PrecioDP != value))
				{
					this.OnPrecioDPChanging(value);
					this.SendPropertyChanging();
					this._PrecioDP = value;
					this.SendPropertyChanged("PrecioDP");
					this.OnPrecioDPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoDP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EstadoDP
		{
			get
			{
				return this._EstadoDP;
			}
			set
			{
				if ((this._EstadoDP != value))
				{
					this.OnEstadoDPChanging(value);
					this.SendPropertyChanging();
					this._EstadoDP = value;
					this.SendPropertyChanged("EstadoDP");
					this.OnEstadoDPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_DetalleProducto", Storage="_Producto", ThisKey="IdP", OtherKey="IdP", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.DetalleProducto.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.DetalleProducto.Add(this);
						this._IdP = value.IdP;
					}
					else
					{
						this._IdP = default(string);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TEmpresa")]
	public partial class Empresa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdE;
		
		private string _NombreE;
		
		private string _CorreoE;
		
		private string _RucE;
		
		private string _TelefonoE;
		
		private string _DescripcionE;
		
		private string _IdV;
		
		private EntitySet<Producto> _Producto;
		
		private EntityRef<Vendedor> _Vendedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEChanging(string value);
    partial void OnIdEChanged();
    partial void OnNombreEChanging(string value);
    partial void OnNombreEChanged();
    partial void OnCorreoEChanging(string value);
    partial void OnCorreoEChanged();
    partial void OnRucEChanging(string value);
    partial void OnRucEChanged();
    partial void OnTelefonoEChanging(string value);
    partial void OnTelefonoEChanged();
    partial void OnDescripcionEChanging(string value);
    partial void OnDescripcionEChanged();
    partial void OnIdVChanging(string value);
    partial void OnIdVChanged();
    #endregion
		
		public Empresa()
		{
			this._Producto = new EntitySet<Producto>(new Action<Producto>(this.attach_Producto), new Action<Producto>(this.detach_Producto));
			this._Vendedor = default(EntityRef<Vendedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdE", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdE
		{
			get
			{
				return this._IdE;
			}
			set
			{
				if ((this._IdE != value))
				{
					this.OnIdEChanging(value);
					this.SendPropertyChanging();
					this._IdE = value;
					this.SendPropertyChanged("IdE");
					this.OnIdEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreE
		{
			get
			{
				return this._NombreE;
			}
			set
			{
				if ((this._NombreE != value))
				{
					this.OnNombreEChanging(value);
					this.SendPropertyChanging();
					this._NombreE = value;
					this.SendPropertyChanged("NombreE");
					this.OnNombreEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorreoE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CorreoE
		{
			get
			{
				return this._CorreoE;
			}
			set
			{
				if ((this._CorreoE != value))
				{
					this.OnCorreoEChanging(value);
					this.SendPropertyChanging();
					this._CorreoE = value;
					this.SendPropertyChanged("CorreoE");
					this.OnCorreoEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RucE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RucE
		{
			get
			{
				return this._RucE;
			}
			set
			{
				if ((this._RucE != value))
				{
					this.OnRucEChanging(value);
					this.SendPropertyChanging();
					this._RucE = value;
					this.SendPropertyChanged("RucE");
					this.OnRucEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TelefonoE
		{
			get
			{
				return this._TelefonoE;
			}
			set
			{
				if ((this._TelefonoE != value))
				{
					this.OnTelefonoEChanging(value);
					this.SendPropertyChanging();
					this._TelefonoE = value;
					this.SendPropertyChanged("TelefonoE");
					this.OnTelefonoEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionE", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
		public string DescripcionE
		{
			get
			{
				return this._DescripcionE;
			}
			set
			{
				if ((this._DescripcionE != value))
				{
					this.OnDescripcionEChanging(value);
					this.SendPropertyChanging();
					this._DescripcionE = value;
					this.SendPropertyChanged("DescripcionE");
					this.OnDescripcionEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdV", DbType="VarChar(5)")]
		public string IdV
		{
			get
			{
				return this._IdV;
			}
			set
			{
				if ((this._IdV != value))
				{
					if (this._Vendedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdVChanging(value);
					this.SendPropertyChanging();
					this._IdV = value;
					this.SendPropertyChanged("IdV");
					this.OnIdVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empresa_Producto", Storage="_Producto", ThisKey="IdE", OtherKey="IdE")]
		public EntitySet<Producto> Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				this._Producto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vendedor_Empresa", Storage="_Vendedor", ThisKey="IdV", OtherKey="IdV", IsForeignKey=true)]
		public Vendedor Vendedor
		{
			get
			{
				return this._Vendedor.Entity;
			}
			set
			{
				Vendedor previousValue = this._Vendedor.Entity;
				if (((previousValue != value) 
							|| (this._Vendedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vendedor.Entity = null;
						previousValue.Empresa.Remove(this);
					}
					this._Vendedor.Entity = value;
					if ((value != null))
					{
						value.Empresa.Add(this);
						this._IdV = value.IdV;
					}
					else
					{
						this._IdV = default(string);
					}
					this.SendPropertyChanged("Vendedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Empresa = this;
		}
		
		private void detach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Empresa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TImagen")]
	public partial class Imagen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdI;
		
		private string _IdP;
		
		private string _NombreI;
		
		private string _ExtensionI;
		
		private EntityRef<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdIChanging(string value);
    partial void OnIdIChanged();
    partial void OnIdPChanging(string value);
    partial void OnIdPChanged();
    partial void OnNombreIChanging(string value);
    partial void OnNombreIChanged();
    partial void OnExtensionIChanging(string value);
    partial void OnExtensionIChanged();
    #endregion
		
		public Imagen()
		{
			this._Producto = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdI", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdI
		{
			get
			{
				return this._IdI;
			}
			set
			{
				if ((this._IdI != value))
				{
					this.OnIdIChanging(value);
					this.SendPropertyChanging();
					this._IdI = value;
					this.SendPropertyChanged("IdI");
					this.OnIdIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdP", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdP
		{
			get
			{
				return this._IdP;
			}
			set
			{
				if ((this._IdP != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPChanging(value);
					this.SendPropertyChanging();
					this._IdP = value;
					this.SendPropertyChanged("IdP");
					this.OnIdPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreI", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreI
		{
			get
			{
				return this._NombreI;
			}
			set
			{
				if ((this._NombreI != value))
				{
					this.OnNombreIChanging(value);
					this.SendPropertyChanging();
					this._NombreI = value;
					this.SendPropertyChanged("NombreI");
					this.OnNombreIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtensionI", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ExtensionI
		{
			get
			{
				return this._ExtensionI;
			}
			set
			{
				if ((this._ExtensionI != value))
				{
					this.OnExtensionIChanging(value);
					this.SendPropertyChanging();
					this._ExtensionI = value;
					this.SendPropertyChanged("ExtensionI");
					this.OnExtensionIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Imagen", Storage="_Producto", ThisKey="IdP", OtherKey="IdP", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Imagen.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Imagen.Add(this);
						this._IdP = value.IdP;
					}
					else
					{
						this._IdP = default(string);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TProducto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdP;
		
		private string _IdE;
		
		private string _IdC;
		
		private string _NombreP;
		
		private string _MarcaP;
		
		private string _DescripcionP;
		
		private EntitySet<DetalleProducto> _DetalleProducto;
		
		private EntitySet<Imagen> _Imagen;
		
		private EntityRef<Empresa> _Empresa;
		
		private EntityRef<Categoria> _Categoria;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPChanging(string value);
    partial void OnIdPChanged();
    partial void OnIdEChanging(string value);
    partial void OnIdEChanged();
    partial void OnIdCChanging(string value);
    partial void OnIdCChanged();
    partial void OnNombrePChanging(string value);
    partial void OnNombrePChanged();
    partial void OnMarcaPChanging(string value);
    partial void OnMarcaPChanged();
    partial void OnDescripcionPChanging(string value);
    partial void OnDescripcionPChanged();
    #endregion
		
		public Producto()
		{
			this._DetalleProducto = new EntitySet<DetalleProducto>(new Action<DetalleProducto>(this.attach_DetalleProducto), new Action<DetalleProducto>(this.detach_DetalleProducto));
			this._Imagen = new EntitySet<Imagen>(new Action<Imagen>(this.attach_Imagen), new Action<Imagen>(this.detach_Imagen));
			this._Empresa = default(EntityRef<Empresa>);
			this._Categoria = default(EntityRef<Categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdP", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdP
		{
			get
			{
				return this._IdP;
			}
			set
			{
				if ((this._IdP != value))
				{
					this.OnIdPChanging(value);
					this.SendPropertyChanging();
					this._IdP = value;
					this.SendPropertyChanged("IdP");
					this.OnIdPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdE
		{
			get
			{
				return this._IdE;
			}
			set
			{
				if ((this._IdE != value))
				{
					if (this._Empresa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdEChanging(value);
					this.SendPropertyChanging();
					this._IdE = value;
					this.SendPropertyChanged("IdE");
					this.OnIdEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdC", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdC
		{
			get
			{
				return this._IdC;
			}
			set
			{
				if ((this._IdC != value))
				{
					if (this._Categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCChanging(value);
					this.SendPropertyChanging();
					this._IdC = value;
					this.SendPropertyChanged("IdC");
					this.OnIdCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreP
		{
			get
			{
				return this._NombreP;
			}
			set
			{
				if ((this._NombreP != value))
				{
					this.OnNombrePChanging(value);
					this.SendPropertyChanging();
					this._NombreP = value;
					this.SendPropertyChanged("NombreP");
					this.OnNombrePChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarcaP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MarcaP
		{
			get
			{
				return this._MarcaP;
			}
			set
			{
				if ((this._MarcaP != value))
				{
					this.OnMarcaPChanging(value);
					this.SendPropertyChanging();
					this._MarcaP = value;
					this.SendPropertyChanged("MarcaP");
					this.OnMarcaPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionP", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
		public string DescripcionP
		{
			get
			{
				return this._DescripcionP;
			}
			set
			{
				if ((this._DescripcionP != value))
				{
					this.OnDescripcionPChanging(value);
					this.SendPropertyChanging();
					this._DescripcionP = value;
					this.SendPropertyChanged("DescripcionP");
					this.OnDescripcionPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_DetalleProducto", Storage="_DetalleProducto", ThisKey="IdP", OtherKey="IdP")]
		public EntitySet<DetalleProducto> DetalleProducto
		{
			get
			{
				return this._DetalleProducto;
			}
			set
			{
				this._DetalleProducto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Imagen", Storage="_Imagen", ThisKey="IdP", OtherKey="IdP")]
		public EntitySet<Imagen> Imagen
		{
			get
			{
				return this._Imagen;
			}
			set
			{
				this._Imagen.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empresa_Producto", Storage="_Empresa", ThisKey="IdE", OtherKey="IdE", IsForeignKey=true)]
		public Empresa Empresa
		{
			get
			{
				return this._Empresa.Entity;
			}
			set
			{
				Empresa previousValue = this._Empresa.Entity;
				if (((previousValue != value) 
							|| (this._Empresa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empresa.Entity = null;
						previousValue.Producto.Remove(this);
					}
					this._Empresa.Entity = value;
					if ((value != null))
					{
						value.Producto.Add(this);
						this._IdE = value.IdE;
					}
					else
					{
						this._IdE = default(string);
					}
					this.SendPropertyChanged("Empresa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Producto", Storage="_Categoria", ThisKey="IdC", OtherKey="IdC", IsForeignKey=true)]
		public Categoria Categoria
		{
			get
			{
				return this._Categoria.Entity;
			}
			set
			{
				Categoria previousValue = this._Categoria.Entity;
				if (((previousValue != value) 
							|| (this._Categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categoria.Entity = null;
						previousValue.Producto.Remove(this);
					}
					this._Categoria.Entity = value;
					if ((value != null))
					{
						value.Producto.Add(this);
						this._IdC = value.IdC;
					}
					else
					{
						this._IdC = default(string);
					}
					this.SendPropertyChanged("Categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetalleProducto(DetalleProducto entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_DetalleProducto(DetalleProducto entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
		
		private void attach_Imagen(Imagen entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Imagen(Imagen entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TUsuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CorreoU;
		
		private string _ContraseniaU;
		
		private EntitySet<Administrador> _Administrador;
		
		private EntitySet<Vendedor> _Vendedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCorreoUChanging(string value);
    partial void OnCorreoUChanged();
    partial void OnContraseniaUChanging(string value);
    partial void OnContraseniaUChanged();
    #endregion
		
		public Usuario()
		{
			this._Administrador = new EntitySet<Administrador>(new Action<Administrador>(this.attach_Administrador), new Action<Administrador>(this.detach_Administrador));
			this._Vendedor = new EntitySet<Vendedor>(new Action<Vendedor>(this.attach_Vendedor), new Action<Vendedor>(this.detach_Vendedor));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorreoU", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CorreoU
		{
			get
			{
				return this._CorreoU;
			}
			set
			{
				if ((this._CorreoU != value))
				{
					this.OnCorreoUChanging(value);
					this.SendPropertyChanging();
					this._CorreoU = value;
					this.SendPropertyChanged("CorreoU");
					this.OnCorreoUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContraseniaU", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ContraseniaU
		{
			get
			{
				return this._ContraseniaU;
			}
			set
			{
				if ((this._ContraseniaU != value))
				{
					this.OnContraseniaUChanging(value);
					this.SendPropertyChanging();
					this._ContraseniaU = value;
					this.SendPropertyChanged("ContraseniaU");
					this.OnContraseniaUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Administrador", Storage="_Administrador", ThisKey="CorreoU", OtherKey="CorreoA")]
		public EntitySet<Administrador> Administrador
		{
			get
			{
				return this._Administrador;
			}
			set
			{
				this._Administrador.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Vendedor", Storage="_Vendedor", ThisKey="CorreoU", OtherKey="CorreoV")]
		public EntitySet<Vendedor> Vendedor
		{
			get
			{
				return this._Vendedor;
			}
			set
			{
				this._Vendedor.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Administrador(Administrador entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Administrador(Administrador entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Vendedor(Vendedor entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Vendedor(Vendedor entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TVendedor")]
	public partial class Vendedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdV;
		
		private string _NombreV;
		
		private string _ApellidosV;
		
		private string _TelefonoV;
		
		private string _DniV;
		
		private string _CorreoV;
		
		private EntitySet<Empresa> _Empresa;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVChanging(string value);
    partial void OnIdVChanged();
    partial void OnNombreVChanging(string value);
    partial void OnNombreVChanged();
    partial void OnApellidosVChanging(string value);
    partial void OnApellidosVChanged();
    partial void OnTelefonoVChanging(string value);
    partial void OnTelefonoVChanged();
    partial void OnDniVChanging(string value);
    partial void OnDniVChanged();
    partial void OnCorreoVChanging(string value);
    partial void OnCorreoVChanged();
    #endregion
		
		public Vendedor()
		{
			this._Empresa = new EntitySet<Empresa>(new Action<Empresa>(this.attach_Empresa), new Action<Empresa>(this.detach_Empresa));
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdV", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdV
		{
			get
			{
				return this._IdV;
			}
			set
			{
				if ((this._IdV != value))
				{
					this.OnIdVChanging(value);
					this.SendPropertyChanging();
					this._IdV = value;
					this.SendPropertyChanged("IdV");
					this.OnIdVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreV
		{
			get
			{
				return this._NombreV;
			}
			set
			{
				if ((this._NombreV != value))
				{
					this.OnNombreVChanging(value);
					this.SendPropertyChanging();
					this._NombreV = value;
					this.SendPropertyChanged("NombreV");
					this.OnNombreVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidosV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ApellidosV
		{
			get
			{
				return this._ApellidosV;
			}
			set
			{
				if ((this._ApellidosV != value))
				{
					this.OnApellidosVChanging(value);
					this.SendPropertyChanging();
					this._ApellidosV = value;
					this.SendPropertyChanged("ApellidosV");
					this.OnApellidosVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoV", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TelefonoV
		{
			get
			{
				return this._TelefonoV;
			}
			set
			{
				if ((this._TelefonoV != value))
				{
					this.OnTelefonoVChanging(value);
					this.SendPropertyChanging();
					this._TelefonoV = value;
					this.SendPropertyChanged("TelefonoV");
					this.OnTelefonoVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DniV", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string DniV
		{
			get
			{
				return this._DniV;
			}
			set
			{
				if ((this._DniV != value))
				{
					this.OnDniVChanging(value);
					this.SendPropertyChanging();
					this._DniV = value;
					this.SendPropertyChanged("DniV");
					this.OnDniVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorreoV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CorreoV
		{
			get
			{
				return this._CorreoV;
			}
			set
			{
				if ((this._CorreoV != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCorreoVChanging(value);
					this.SendPropertyChanging();
					this._CorreoV = value;
					this.SendPropertyChanged("CorreoV");
					this.OnCorreoVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vendedor_Empresa", Storage="_Empresa", ThisKey="IdV", OtherKey="IdV")]
		public EntitySet<Empresa> Empresa
		{
			get
			{
				return this._Empresa;
			}
			set
			{
				this._Empresa.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Vendedor", Storage="_Usuario", ThisKey="CorreoV", OtherKey="CorreoU", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Vendedor.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Vendedor.Add(this);
						this._CorreoV = value.CorreoU;
					}
					else
					{
						this._CorreoV = default(string);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Empresa(Empresa entity)
		{
			this.SendPropertyChanging();
			entity.Vendedor = this;
		}
		
		private void detach_Empresa(Empresa entity)
		{
			this.SendPropertyChanging();
			entity.Vendedor = null;
		}
	}
	
	public partial class spActualizarDatosVendedorResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spActualizarDatosVendedorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(34) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spAgregarImagenResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spAgregarImagenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spAgregarVendedorEmpresaResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spAgregarVendedorEmpresaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spCambiarContraseniaVendedorResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spCambiarContraseniaVendedorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spEliminarImagenResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spEliminarImagenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spEliminarProductoResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spEliminarProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spListarCategoriaResult
	{
		
		private int _IdC;
		
		private string _NombreC;
		
		private System.Nullable<int> _IdCatPadre;
		
		public spListarCategoriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdC", DbType="Int NOT NULL")]
		public int IdC
		{
			get
			{
				return this._IdC;
			}
			set
			{
				if ((this._IdC != value))
				{
					this._IdC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreC
		{
			get
			{
				return this._NombreC;
			}
			set
			{
				if ((this._NombreC != value))
				{
					this._NombreC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCatPadre", DbType="Int")]
		public System.Nullable<int> IdCatPadre
		{
			get
			{
				return this._IdCatPadre;
			}
			set
			{
				if ((this._IdCatPadre != value))
				{
					this._IdCatPadre = value;
				}
			}
		}
	}
	
	public partial class spListarEmpresaResult
	{
		
		private int _IdE;
		
		private string _NombreE;
		
		private string _CorreoE;
		
		private string _RucE;
		
		private string _TelefonoE;
		
		private string _DescripcionE;
		
		public spListarEmpresaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdE", DbType="Int NOT NULL")]
		public int IdE
		{
			get
			{
				return this._IdE;
			}
			set
			{
				if ((this._IdE != value))
				{
					this._IdE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreE
		{
			get
			{
				return this._NombreE;
			}
			set
			{
				if ((this._NombreE != value))
				{
					this._NombreE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorreoE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CorreoE
		{
			get
			{
				return this._CorreoE;
			}
			set
			{
				if ((this._CorreoE != value))
				{
					this._CorreoE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RucE", DbType="VarChar(50)")]
		public string RucE
		{
			get
			{
				return this._RucE;
			}
			set
			{
				if ((this._RucE != value))
				{
					this._RucE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoE", DbType="VarChar(20)")]
		public string TelefonoE
		{
			get
			{
				return this._TelefonoE;
			}
			set
			{
				if ((this._TelefonoE != value))
				{
					this._TelefonoE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionE", DbType="VarChar(300)")]
		public string DescripcionE
		{
			get
			{
				return this._DescripcionE;
			}
			set
			{
				if ((this._DescripcionE != value))
				{
					this._DescripcionE = value;
				}
			}
		}
	}
	
	public partial class spListarImagenResult
	{
		
		private int _IdI;
		
		private int _IdP;
		
		private System.Data.Linq.Binary _ImagenI;
		
		private string _NombreI;
		
		public spListarImagenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdI", DbType="Int NOT NULL")]
		public int IdI
		{
			get
			{
				return this._IdI;
			}
			set
			{
				if ((this._IdI != value))
				{
					this._IdI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdP", DbType="Int NOT NULL")]
		public int IdP
		{
			get
			{
				return this._IdP;
			}
			set
			{
				if ((this._IdP != value))
				{
					this._IdP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagenI", DbType="Image")]
		public System.Data.Linq.Binary ImagenI
		{
			get
			{
				return this._ImagenI;
			}
			set
			{
				if ((this._ImagenI != value))
				{
					this._ImagenI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreI", DbType="VarChar(50)")]
		public string NombreI
		{
			get
			{
				return this._NombreI;
			}
			set
			{
				if ((this._NombreI != value))
				{
					this._NombreI = value;
				}
			}
		}
	}
	
	public partial class spListarProductoResult
	{
		
		private int _IdP;
		
		private int _IdE;
		
		private int _IdC;
		
		private string _NombreP;
		
		private System.Data.Linq.Binary _ImagenRef;
		
		private string _MarcaP;
		
		private string _DescripcionP;
		
		public spListarProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdP", DbType="Int NOT NULL")]
		public int IdP
		{
			get
			{
				return this._IdP;
			}
			set
			{
				if ((this._IdP != value))
				{
					this._IdP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdE", DbType="Int NOT NULL")]
		public int IdE
		{
			get
			{
				return this._IdE;
			}
			set
			{
				if ((this._IdE != value))
				{
					this._IdE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdC", DbType="Int NOT NULL")]
		public int IdC
		{
			get
			{
				return this._IdC;
			}
			set
			{
				if ((this._IdC != value))
				{
					this._IdC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreP
		{
			get
			{
				return this._NombreP;
			}
			set
			{
				if ((this._NombreP != value))
				{
					this._NombreP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagenRef", DbType="Image")]
		public System.Data.Linq.Binary ImagenRef
		{
			get
			{
				return this._ImagenRef;
			}
			set
			{
				if ((this._ImagenRef != value))
				{
					this._ImagenRef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarcaP", DbType="VarChar(50)")]
		public string MarcaP
		{
			get
			{
				return this._MarcaP;
			}
			set
			{
				if ((this._MarcaP != value))
				{
					this._MarcaP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionP", DbType="VarChar(300)")]
		public string DescripcionP
		{
			get
			{
				return this._DescripcionP;
			}
			set
			{
				if ((this._DescripcionP != value))
				{
					this._DescripcionP = value;
				}
			}
		}
	}
	
	public partial class spLoginVendedorResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spLoginVendedorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(50)")]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spMisImagenesResult
	{
		
		private int _CImagen;
		
		private int _CProducto;
		
		private string _Nombre;
		
		private System.Data.Linq.Binary _imagen;
		
		public spMisImagenesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CImagen", DbType="Int NOT NULL")]
		public int CImagen
		{
			get
			{
				return this._CImagen;
			}
			set
			{
				if ((this._CImagen != value))
				{
					this._CImagen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CProducto", DbType="Int NOT NULL")]
		public int CProducto
		{
			get
			{
				return this._CProducto;
			}
			set
			{
				if ((this._CProducto != value))
				{
					this._CProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagen", DbType="Image")]
		public System.Data.Linq.Binary imagen
		{
			get
			{
				return this._imagen;
			}
			set
			{
				if ((this._imagen != value))
				{
					this._imagen = value;
				}
			}
		}
	}
	
	public partial class spListarCatalogoResult
	{
		
		private int _IdP;
		
		private string _NombreP;
		
		private string _MarcaP;
		
		private string _DescripcionP;
		
		private System.Data.Linq.Binary _ImagenRef;
		
		public spListarCatalogoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdP", DbType="Int NOT NULL")]
		public int IdP
		{
			get
			{
				return this._IdP;
			}
			set
			{
				if ((this._IdP != value))
				{
					this._IdP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreP
		{
			get
			{
				return this._NombreP;
			}
			set
			{
				if ((this._NombreP != value))
				{
					this._NombreP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarcaP", DbType="VarChar(50)")]
		public string MarcaP
		{
			get
			{
				return this._MarcaP;
			}
			set
			{
				if ((this._MarcaP != value))
				{
					this._MarcaP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionP", DbType="VarChar(300)")]
		public string DescripcionP
		{
			get
			{
				return this._DescripcionP;
			}
			set
			{
				if ((this._DescripcionP != value))
				{
					this._DescripcionP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagenRef", DbType="Image")]
		public System.Data.Linq.Binary ImagenRef
		{
			get
			{
				return this._ImagenRef;
			}
			set
			{
				if ((this._ImagenRef != value))
				{
					this._ImagenRef = value;
				}
			}
		}
	}
	
	public partial class spActualizarProductoResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spActualizarProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(34) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spMisProductosResult
	{
		
		private int _CProducto;
		
		private int _CCategoria;
		
		private string _Nombre;
		
		private string _Marca;
		
		private System.Nullable<int> _Stock;
		
		private float _Precio;
		
		private string _Descripcion;
		
		private System.Data.Linq.Binary _imagen;
		
		public spMisProductosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CProducto", DbType="Int NOT NULL")]
		public int CProducto
		{
			get
			{
				return this._CProducto;
			}
			set
			{
				if ((this._CProducto != value))
				{
					this._CProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCategoria", DbType="Int NOT NULL")]
		public int CCategoria
		{
			get
			{
				return this._CCategoria;
			}
			set
			{
				if ((this._CCategoria != value))
				{
					this._CCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="VarChar(50)")]
		public string Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this._Marca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stock", DbType="Int")]
		public System.Nullable<int> Stock
		{
			get
			{
				return this._Stock;
			}
			set
			{
				if ((this._Stock != value))
				{
					this._Stock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Real NOT NULL")]
		public float Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this._Precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(300)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagen", DbType="Image")]
		public System.Data.Linq.Binary imagen
		{
			get
			{
				return this._imagen;
			}
			set
			{
				if ((this._imagen != value))
				{
					this._imagen = value;
				}
			}
		}
	}
	
	public partial class spAgregarProductoResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spAgregarProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spListarProductoDetallesResult
	{
		
		private int _IdP;
		
		private string _NombreEmpresa;
		
		private int _IdC;
		
		private string _NombreP;
		
		private System.Data.Linq.Binary _ImagenRef;
		
		private string _MarcaP;
		
		private System.Nullable<int> _StockDP;
		
		private float _PrecioDP;
		
		private string _DescripcionP;
		
		public spListarProductoDetallesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdP", DbType="Int NOT NULL")]
		public int IdP
		{
			get
			{
				return this._IdP;
			}
			set
			{
				if ((this._IdP != value))
				{
					this._IdP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreEmpresa", DbType="VarChar(50)")]
		public string NombreEmpresa
		{
			get
			{
				return this._NombreEmpresa;
			}
			set
			{
				if ((this._NombreEmpresa != value))
				{
					this._NombreEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdC", DbType="Int NOT NULL")]
		public int IdC
		{
			get
			{
				return this._IdC;
			}
			set
			{
				if ((this._IdC != value))
				{
					this._IdC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreP
		{
			get
			{
				return this._NombreP;
			}
			set
			{
				if ((this._NombreP != value))
				{
					this._NombreP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagenRef", DbType="Image")]
		public System.Data.Linq.Binary ImagenRef
		{
			get
			{
				return this._ImagenRef;
			}
			set
			{
				if ((this._ImagenRef != value))
				{
					this._ImagenRef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarcaP", DbType="VarChar(50)")]
		public string MarcaP
		{
			get
			{
				return this._MarcaP;
			}
			set
			{
				if ((this._MarcaP != value))
				{
					this._MarcaP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockDP", DbType="Int")]
		public System.Nullable<int> StockDP
		{
			get
			{
				return this._StockDP;
			}
			set
			{
				if ((this._StockDP != value))
				{
					this._StockDP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioDP", DbType="Real NOT NULL")]
		public float PrecioDP
		{
			get
			{
				return this._PrecioDP;
			}
			set
			{
				if ((this._PrecioDP != value))
				{
					this._PrecioDP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionP", DbType="VarChar(300)")]
		public string DescripcionP
		{
			get
			{
				return this._DescripcionP;
			}
			set
			{
				if ((this._DescripcionP != value))
				{
					this._DescripcionP = value;
				}
			}
		}
	}
	
	public partial class spListarfotosDeProductoResult
	{
		
		private System.Data.Linq.Binary _ImagenI;
		
		private string _NombreI;
		
		public spListarfotosDeProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagenI", DbType="Image")]
		public System.Data.Linq.Binary ImagenI
		{
			get
			{
				return this._ImagenI;
			}
			set
			{
				if ((this._ImagenI != value))
				{
					this._ImagenI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreI", DbType="VarChar(50)")]
		public string NombreI
		{
			get
			{
				return this._NombreI;
			}
			set
			{
				if ((this._NombreI != value))
				{
					this._NombreI = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
